services:
  springboot-app:
    build: .
    image: classroommission-imagem
    container_name: classroommission-container
    ports:
      - "8099:8099"
    volumes:
      - ./src/main/java/com/classroommission/db/books.json:/db/books.json